event_registration.settings:
  type: config_object
  label: 'Event Registration Settings'
  mapping:
    admin_email:
      type: email
      label: 'Admin notification email address'
    admin_notification_enabled:
      type: boolean
      label: 'Enable admin notifications'
